### ISSUE TITLE
Create C# examples for Dependency Injection

### ISSUE THREAD

**Issue by olandese** [microsoft/kiota-samples#2104]
Please create C# examples how to deal with DI and clients generated in Kiota

**Comment by MASS59** [comment]
#2461

**Comment by MASS59** [comment]
> #2461

**Comment by jacobmohl** [comment]
We also need guidelines for this. Azure.Core has as an example "AddAzureClients". Does the Kiota tooling have something similar?

**Comment by baywet** [comment]
Hey everyone,
Thanks for using kiota and sorry about the delay in the answer, I wasn't watching issues in this repository for some reason.
I have created an issue in our documentation repository to reflect this.
https://github.com/MicrosoftDocs/openapi-docs/issues/37
Closing

**Comment by svrooij** [comment]
@olandese and everybody following along here, I've just created a complete example on how you could do this. https://github.com/svrooij/KiotaWithDependencyInjection
