### ISSUE TITLE
Authentication for APIs with basic authentication and bearer 

### ISSUE THREAD

**Issue by robertvanmolken** [microsoft/kiota-samples#3230]
I'm looking for an example implementation that can call APIs protected by either basic auth as bearer token.

I see that there is a BaseBearerToken provider but can find any example implementation. 

It requires an AccessTokenProvider and I am struggling how to implement that.

Can this please be added to the documentation

**Comment by jakejscott** [comment]
Examples for dotnet would be great :)

**Comment by baywet** [comment]
provided a bit of guidance, would either of you be willing to submit a pull request?

**Comment by pickettd** [comment]
@robertvanmolken and @jakejscott - I'll paste a snippet below that worked for me for using Kiota with bearer auth in dotnet. And @baywet I'm willing to submit a PR if it is useful

```using KiotaPosts.Client;
using KiotaPosts.Client.Models;
using Microsoft.Kiota.Abstractions.Authentication;
using Microsoft.Kiota.Http.HttpClientLibrary;

// authentication provider using class from below
TokenProvider myTokenProvider = new TokenProvider();
var authProvider = new BaseBearerTokenAuthenticationProvider(myTokenProvider);
// Create request adapter using the HttpClient-based implementation
var adapter = new HttpClientRequestAdapter(authProvider);
// Create the API client
var client = new Client(adapter);

try
{
    var findId = "<example_cust_id>";

    var idCust = await client.Customers[findId].GetAsync();
    Console.WriteLine($"Retrieved by id: {idCust.Customer.Email}");
    Console.WriteLine($"Retrieved by id: {idCust.Customer.Id}");
}
catch (Exception ex)
{
    Console.WriteLine($"ERROR: {ex.Message}");
    Console.WriteLine(ex.StackTrace);
}

internal class TokenProvider : IAccessTokenProvider
{
    public AllowedHostsValidator AllowedHostsValidator { get; }

    public Task<string> GetAuthorizationTokenAsync(
        Uri uri,
        Dictionary<string, object>? additionalAuthenticationContext = null,
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult("<insert_bearer_token>");
    }
}

**Comment by baywet** [comment]
@pickettd I somehow missed that response until it was recently pointed to me, apologies.
It'd might be worth having this sample in the documentation as a new section.
if you're still interested in following up. Can you please create an issue here?
https://github.com/MicrosoftDocs/openapi-docs/issues
