### ISSUE TITLE
Update the Support.md file to include the relevant support options

### ISSUE THREAD

**Issue by PureKrome** [microsoft/kiota-samples#47]
The default MS support.md doc (located at https://github.com/microsoft/kiota-samples/blob/main/SUPPORT.md) hasn't been updated.

It still includes the default template text, etc. 

Needs to be:
- 👀 Reviewed/read
- 🖊️ Updated accordingly to what options you want.

🍰

**Comment by baywet** [comment]
Hey @PureKrome 
Thanks for letting us know. For some reason I didn't see the notification coming through when you originally created the issue.
