### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by chandraarora** [microsoft/kiota-samples#6753]
Hi 

I just clone the sample project and run the typescript script project. I get error 

ic import() which is available in all CommonJS modules.
    at Object.<anonymous> (kiota-samples\get-started\quickstart\typescript\out\index.js:15:30) {
  code: 'ERR_REQUIRE_ESM'
}

Could you please let me know what is wrong here?

Thanks
Chandra

**Comment by baywet** [comment]
Hi @chandraarora 
Thank you for using kiota and for reaching out.

The samples were trailing behind the ongoing development efforts. I have put a PR together to refresh them.
#6755

Let us know if you have any additional comments or questions.
